# Default values for dlsp.
# 나머지는 고정하고 수정할 부분만 노출
image:
  repository: github.com/1eedaegon/distributed-logging-storage-practice
  tag: 0.0.1
  pullPolicy: IfNotPresent
serfPort: 8401
rpcPort: 8400
replicas: 3
storage: 1Gi
